# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PlotGUI_v2.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1085, 885)
        self.Window = QtWidgets.QLabel(Dialog)
        self.Window.setGeometry(QtCore.QRect(60, 150, 1001, 661))
        self.Window.setStyleSheet("background-color:white;\n"
"border-radius:20px;\n"
"border:2px solid black;")
        self.Window.setText("")
        self.Window.setObjectName("Window")
        self.Prob_Window = QtWidgets.QLabel(Dialog)
        self.Prob_Window.setGeometry(QtCore.QRect(90, 557, 211, 211))
        self.Prob_Window.setStyleSheet("background-color:white;\n"
"border-radius:10px;\n"
"border:2px solid black;")
        self.Prob_Window.setText("")
        self.Prob_Window.setObjectName("Prob_Window")
        self.Title = QtWidgets.QLabel(Dialog)
        self.Title.setGeometry(QtCore.QRect(60, 80, 1001, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Title.setFont(font)
        self.Title.setStyleSheet("background-color:rgb(46, 77, 255);\n"
"border-width:1px;\n"
"border-color:black;\n"
"border-radius:30px;\n"
"color:white;")
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.X_WIndow = QtWidgets.QLabel(Dialog)
        self.X_WIndow.setGeometry(QtCore.QRect(340, 200, 691, 571))
        self.X_WIndow.setStyleSheet("background-color:white;\n"
"border-radius:10px;\n"
"border:2px solid black;")
        self.X_WIndow.setText("")
        self.X_WIndow.setObjectName("X_WIndow")
        self.Prob1 = QtWidgets.QProgressBar(Dialog)
        self.Prob1.setGeometry(QtCore.QRect(170, 660, 121, 28))
        self.Prob1.setStyleSheet("QProgressBar {border:1px solid rgb(145, 145, 145);background:rgb(255, 255, 255);font-weight:bold;} QProgressBar::chunk {background: rgb(15, 27, 255);}")
        self.Prob1.setMinimum(0)
        self.Prob1.setProperty("value", 0)
        self.Prob1.setAlignment(QtCore.Qt.AlignCenter)
        self.Prob1.setObjectName("Prob1")
        self.Select_File_Back = QtWidgets.QLabel(Dialog)
        self.Select_File_Back.setGeometry(QtCore.QRect(95, 195, 161, 91))
        self.Select_File_Back.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0.244, y1:1, x2:0.199, y2:0.0280, stop:0 rgba(11,11,204,255), stop:1 rgba(200,200,200,255));\n"
"border-width:1px;\n"
"border-color:black;\n"
"border-radius:15px;\n"
"color:black;")
        self.Select_File_Back.setText("")
        self.Select_File_Back.setObjectName("Select_File_Back")
        self.Select_File = QtWidgets.QPushButton(Dialog)
        self.Select_File.setGeometry(QtCore.QRect(100, 200, 151, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Select_File.setFont(font)
        self.Select_File.setStyleSheet("background-color:rgb(20, 85, 255);\n"
"border-radius:10px;\n"
"color:white;\n"
"\n"
"")
        self.Select_File.setObjectName("Select_File")
        self.Execution_Back = QtWidgets.QLabel(Dialog)
        self.Execution_Back.setGeometry(QtCore.QRect(95, 315, 161, 91))
        self.Execution_Back.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0.244, y1:1, x2:0.199, y2:0.0280, stop:0 rgba(11,11,204,255), stop:1 rgba(200,200,200,255));\n"
"border-width:1px;\n"
"border-color:black;\n"
"border-radius:15px;\n"
"color:black;")
        self.Execution_Back.setText("")
        self.Execution_Back.setObjectName("Execution_Back")
        self.Execution = QtWidgets.QPushButton(Dialog)
        self.Execution.setGeometry(QtCore.QRect(100, 320, 151, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Execution.setFont(font)
        self.Execution.setStyleSheet("background-color:rgb(20, 85, 255);\n"
"border-radius:10px;\n"
"color:white;")
        self.Execution.setObjectName("Execution")
        self.Prob2 = QtWidgets.QProgressBar(Dialog)
        self.Prob2.setGeometry(QtCore.QRect(170, 710, 121, 28))
        self.Prob2.setStyleSheet("QProgressBar {border:1px solid rgb(145, 145, 145);background:rgb(255, 255, 255);font-weight:bold;} QProgressBar::chunk {background: rgb(185, 0, 0)\n"
";}")
        self.Prob2.setProperty("value", 0)
        self.Prob2.setAlignment(QtCore.Qt.AlignCenter)
        self.Prob2.setObjectName("Prob2")
        self.Prob1_Text = QtWidgets.QLabel(Dialog)
        self.Prob1_Text.setGeometry(QtCore.QRect(110, 657, 71, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Prob1_Text.setFont(font)
        self.Prob1_Text.setStyleSheet("color: rgb(15, 27, 255);\n"
"font-weight:bold;")
        self.Prob1_Text.setObjectName("Prob1_Text")
        self.Prob2_Text = QtWidgets.QLabel(Dialog)
        self.Prob2_Text.setGeometry(QtCore.QRect(110, 707, 71, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Prob2_Text.setFont(font)
        self.Prob2_Text.setStyleSheet("color:rgb(185, 0, 0);\n"
"font-weight:bold;")
        self.Prob2_Text.setObjectName("Prob2_Text")
        self.Classification_Result = QtWidgets.QLabel(Dialog)
        self.Classification_Result.setGeometry(QtCore.QRect(120, 577, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(True)
        self.Classification_Result.setFont(font)
        self.Classification_Result.setAlignment(QtCore.Qt.AlignCenter)
        self.Classification_Result.setObjectName("Classification_Result")
        self.X_Text = QtWidgets.QLabel(Dialog)
        self.X_Text.setGeometry(QtCore.QRect(360, 220, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.X_Text.setFont(font)
        self.X_Text.setStyleSheet("background-color:rgb(20, 85, 255);\n"
"border-radius:10px;\n"
"color:white;")
        self.X_Text.setAlignment(QtCore.Qt.AlignCenter)
        self.X_Text.setObjectName("X_Text")
        self.X_In_Window = QtWidgets.QLabel(Dialog)
        self.X_In_Window.setGeometry(QtCore.QRect(360, 290, 511, 461))
        self.X_In_Window.setStyleSheet("background-color:white;\n"
"border-radius:10px;\n"
"color:white;")
        self.X_In_Window.setText("")
        self.X_In_Window.setObjectName("X_In_Window")
        self.X_Result = QtWidgets.QLabel(Dialog)
        self.X_Result.setGeometry(QtCore.QRect(360, 300, 651, 441))
        self.X_Result.setStyleSheet("border:1px solid rgb(165, 165, 165);")
        self.X_Result.setText("")
        self.X_Result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.X_Result.setObjectName("X_Result")
        self.pushButton_pre = QtWidgets.QPushButton(Dialog)
        self.pushButton_pre.setGeometry(QtCore.QRect(690, 230, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_pre.setFont(font)
        self.pushButton_pre.setObjectName("pushButton_pre")
        self.LIME = QtWidgets.QLabel(Dialog)
        self.LIME.setGeometry(QtCore.QRect(878, 240, 21, 21))
        self.LIME.setText("")
        self.LIME.setObjectName("LIME")
        self.SHAP = QtWidgets.QLabel(Dialog)
        self.SHAP.setGeometry(QtCore.QRect(955, 240, 21, 21))
        self.SHAP.setText("")
        self.SHAP.setObjectName("SHAP")
        self.Input_Title = QtWidgets.QLabel(Dialog)
        self.Input_Title.setGeometry(QtCore.QRect(360, 300, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Input_Title.setFont(font)
        self.Input_Title.setStyleSheet("border:1.5px solid rgb(165, 165, 165);\n"
"background-color:rgb(14, 59, 162);\n"
"color:white;")
        self.Input_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Input_Title.setObjectName("Input_Title")
        self.Value_Title = QtWidgets.QLabel(Dialog)
        self.Value_Title.setGeometry(QtCore.QRect(660, 300, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Value_Title.setFont(font)
        self.Value_Title.setStyleSheet("border:1.5px solid rgb(165, 165, 165);\n"
"background-color:rgb(14, 59, 162);\n"
"color:white;")
        self.Value_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Value_Title.setObjectName("Value_Title")
        self.X_Title = QtWidgets.QLabel(Dialog)
        self.X_Title.setGeometry(QtCore.QRect(710, 300, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.X_Title.setFont(font)
        self.X_Title.setStyleSheet("border:1.5px solid rgb(165, 165, 165);\n"
"background-color:rgb(14, 59, 162);\n"
"color:white;")
        self.X_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.X_Title.setObjectName("X_Title")
        self.X_LText_0 = QtWidgets.QLabel(Dialog)
        self.X_LText_0.setGeometry(QtCore.QRect(360, 340, 301, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.X_LText_0.setFont(font)
        self.X_LText_0.setStyleSheet("border:1px solid rgb(165, 165, 165);\n"
"color:rgb(185, 0, 0);\n"
"font-weight:bold;")
        self.X_LText_0.setText("")
        self.X_LText_0.setAlignment(QtCore.Qt.AlignCenter)
        self.X_LText_0.setObjectName("X_LText_0")
        self.X_LText_1 = QtWidgets.QLabel(Dialog)
        self.X_LText_1.setGeometry(QtCore.QRect(360, 380, 301, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.X_LText_1.setFont(font)
        self.X_LText_1.setStyleSheet("border:1px solid rgb(165, 165, 165);\n"
"color:rgb(185, 0, 0);\n"
"font-weight:bold;")
        self.X_LText_1.setText("")
        self.X_LText_1.setAlignment(QtCore.Qt.AlignCenter)
        self.X_LText_1.setObjectName("X_LText_1")
        self.X_LText_2 = QtWidgets.QLabel(Dialog)
        self.X_LText_2.setGeometry(QtCore.QRect(360, 420, 301, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.X_LText_2.setFont(font)
        self.X_LText_2.setStyleSheet("border:1px solid rgb(165, 165, 165);\n"
"color:rgb(185, 0, 0);\n"
"font-weight:bold;")
        self.X_LText_2.setText("")
        self.X_LText_2.setAlignment(QtCore.Qt.AlignCenter)
        self.X_LText_2.setObjectName("X_LText_2")
        self.X_LText_3 = QtWidgets.QLabel(Dialog)
        self.X_LText_3.setGeometry(QtCore.QRect(360, 460, 301, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.X_LText_3.setFont(font)
        self.X_LText_3.setStyleSheet("border:1px solid rgb(165, 165, 165);\n"
"color:rgb(185, 0, 0);\n"
"font-weight:bold;")
        self.X_LText_3.setText("")
        self.X_LText_3.setAlignment(QtCore.Qt.AlignCenter)
        self.X_LText_3.setObjectName("X_LText_3")
        self.X_LText_4 = QtWidgets.QLabel(Dialog)
        self.X_LText_4.setGeometry(QtCore.QRect(360, 500, 301, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.X_LText_4.setFont(font)
        self.X_LText_4.setStyleSheet("border:1px solid rgb(165, 165, 165);\n"
"color:rgb(185, 0, 0);\n"
"font-weight:bold;")
        self.X_LText_4.setText("")
        self.X_LText_4.setAlignment(QtCore.Qt.AlignCenter)
        self.X_LText_4.setObjectName("X_LText_4")
        self.X_RText_0 = QtWidgets.QLabel(Dialog)
        self.X_RText_0.setGeometry(QtCore.QRect(360, 540, 301, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.X_RText_0.setFont(font)
        self.X_RText_0.setStyleSheet("border:1px solid rgb(165, 165, 165);\n"
"color: rgb(15, 27, 255);\n"
"font-weight:bold;\n"
"")
        self.X_RText_0.setText("")
        self.X_RText_0.setAlignment(QtCore.Qt.AlignCenter)
        self.X_RText_0.setObjectName("X_RText_0")
        self.X_RText_1 = QtWidgets.QLabel(Dialog)
        self.X_RText_1.setGeometry(QtCore.QRect(360, 580, 301, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.X_RText_1.setFont(font)
        self.X_RText_1.setStyleSheet("border:1px solid rgb(165, 165, 165);\n"
"color: rgb(15, 27, 255);\n"
"font-weight:bold;\n"
"")
        self.X_RText_1.setText("")
        self.X_RText_1.setAlignment(QtCore.Qt.AlignCenter)
        self.X_RText_1.setObjectName("X_RText_1")
        self.X_RText_2 = QtWidgets.QLabel(Dialog)
        self.X_RText_2.setGeometry(QtCore.QRect(360, 620, 301, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.X_RText_2.setFont(font)
        self.X_RText_2.setStyleSheet("border:1px solid rgb(165, 165, 165);\n"
"color: rgb(15, 27, 255);\n"
"font-weight:bold;\n"
"")
        self.X_RText_2.setText("")
        self.X_RText_2.setAlignment(QtCore.Qt.AlignCenter)
        self.X_RText_2.setObjectName("X_RText_2")
        self.X_RText_3 = QtWidgets.QLabel(Dialog)
        self.X_RText_3.setGeometry(QtCore.QRect(360, 660, 301, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.X_RText_3.setFont(font)
        self.X_RText_3.setStyleSheet("border:1px solid rgb(165, 165, 165);\n"
"color: rgb(15, 27, 255);\n"
"font-weight:bold;\n"
"")
        self.X_RText_3.setText("")
        self.X_RText_3.setAlignment(QtCore.Qt.AlignCenter)
        self.X_RText_3.setObjectName("X_RText_3")
        self.X_RText_4 = QtWidgets.QLabel(Dialog)
        self.X_RText_4.setGeometry(QtCore.QRect(360, 700, 301, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.X_RText_4.setFont(font)
        self.X_RText_4.setStyleSheet("border:1px solid rgb(165, 165, 165);\n"
"color: rgb(15, 27, 255);\n"
"font-weight:bold;\n"
"")
        self.X_RText_4.setText("")
        self.X_RText_4.setAlignment(QtCore.Qt.AlignCenter)
        self.X_RText_4.setObjectName("X_RText_4")
        self.X_LValue_0 = QtWidgets.QLabel(Dialog)
        self.X_LValue_0.setGeometry(QtCore.QRect(660, 340, 51, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.X_LValue_0.setFont(font)
        self.X_LValue_0.setStyleSheet("border:1px solid rgb(165, 165, 165);\n"
"color:rgb(185, 0, 0);\n"
"font-weight:bold;")
        self.X_LValue_0.setText("")
        self.X_LValue_0.setAlignment(QtCore.Qt.AlignCenter)
        self.X_LValue_0.setObjectName("X_LValue_0")
        self.X_LValue_1 = QtWidgets.QLabel(Dialog)
        self.X_LValue_1.setGeometry(QtCore.QRect(660, 380, 51, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.X_LValue_1.setFont(font)
        self.X_LValue_1.setStyleSheet("border:1px solid rgb(165, 165, 165);\n"
"color:rgb(185, 0, 0);\n"
"font-weight:bold;")
        self.X_LValue_1.setText("")
        self.X_LValue_1.setAlignment(QtCore.Qt.AlignCenter)
        self.X_LValue_1.setObjectName("X_LValue_1")
        self.X_LValue_2 = QtWidgets.QLabel(Dialog)
        self.X_LValue_2.setGeometry(QtCore.QRect(660, 420, 51, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.X_LValue_2.setFont(font)
        self.X_LValue_2.setStyleSheet("border:1px solid rgb(165, 165, 165);\n"
"color:rgb(185, 0, 0);\n"
"font-weight:bold;")
        self.X_LValue_2.setText("")
        self.X_LValue_2.setAlignment(QtCore.Qt.AlignCenter)
        self.X_LValue_2.setObjectName("X_LValue_2")
        self.X_LValue_3 = QtWidgets.QLabel(Dialog)
        self.X_LValue_3.setGeometry(QtCore.QRect(660, 460, 51, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.X_LValue_3.setFont(font)
        self.X_LValue_3.setStyleSheet("border:1px solid rgb(165, 165, 165);\n"
"color:rgb(185, 0, 0);\n"
"font-weight:bold;")
        self.X_LValue_3.setText("")
        self.X_LValue_3.setAlignment(QtCore.Qt.AlignCenter)
        self.X_LValue_3.setObjectName("X_LValue_3")
        self.X_LValue_4 = QtWidgets.QLabel(Dialog)
        self.X_LValue_4.setGeometry(QtCore.QRect(660, 500, 51, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.X_LValue_4.setFont(font)
        self.X_LValue_4.setStyleSheet("border:1px solid rgb(165, 165, 165);\n"
"color:rgb(185, 0, 0);\n"
"font-weight:bold;")
        self.X_LValue_4.setText("")
        self.X_LValue_4.setAlignment(QtCore.Qt.AlignCenter)
        self.X_LValue_4.setObjectName("X_LValue_4")
        self.X_RValue_0 = QtWidgets.QLabel(Dialog)
        self.X_RValue_0.setGeometry(QtCore.QRect(660, 540, 51, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.X_RValue_0.setFont(font)
        self.X_RValue_0.setStyleSheet("border:1px solid rgb(165, 165, 165);\n"
"color: rgb(15, 27, 255);\n"
"font-weight:bold;\n"
"")
        self.X_RValue_0.setText("")
        self.X_RValue_0.setAlignment(QtCore.Qt.AlignCenter)
        self.X_RValue_0.setObjectName("X_RValue_0")
        self.X_RValue_1 = QtWidgets.QLabel(Dialog)
        self.X_RValue_1.setGeometry(QtCore.QRect(660, 580, 51, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.X_RValue_1.setFont(font)
        self.X_RValue_1.setStyleSheet("border:1px solid rgb(165, 165, 165);\n"
"color: rgb(15, 27, 255);\n"
"font-weight:bold;\n"
"")
        self.X_RValue_1.setText("")
        self.X_RValue_1.setAlignment(QtCore.Qt.AlignCenter)
        self.X_RValue_1.setObjectName("X_RValue_1")
        self.X_RValue_2 = QtWidgets.QLabel(Dialog)
        self.X_RValue_2.setGeometry(QtCore.QRect(660, 620, 51, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.X_RValue_2.setFont(font)
        self.X_RValue_2.setStyleSheet("border:1px solid rgb(165, 165, 165);\n"
"color: rgb(15, 27, 255);\n"
"font-weight:bold;\n"
"")
        self.X_RValue_2.setText("")
        self.X_RValue_2.setAlignment(QtCore.Qt.AlignCenter)
        self.X_RValue_2.setObjectName("X_RValue_2")
        self.X_RValue_3 = QtWidgets.QLabel(Dialog)
        self.X_RValue_3.setGeometry(QtCore.QRect(660, 660, 51, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.X_RValue_3.setFont(font)
        self.X_RValue_3.setStyleSheet("border:1px solid rgb(165, 165, 165);\n"
"color: rgb(15, 27, 255);\n"
"font-weight:bold;\n"
"")
        self.X_RValue_3.setText("")
        self.X_RValue_3.setAlignment(QtCore.Qt.AlignCenter)
        self.X_RValue_3.setObjectName("X_RValue_3")
        self.X_RValue_4 = QtWidgets.QLabel(Dialog)
        self.X_RValue_4.setGeometry(QtCore.QRect(660, 700, 51, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.X_RValue_4.setFont(font)
        self.X_RValue_4.setStyleSheet("border:1px solid rgb(165, 165, 165);\n"
"color: rgb(15, 27, 255);\n"
"font-weight:bold;\n"
"")
        self.X_RValue_4.setText("")
        self.X_RValue_4.setAlignment(QtCore.Qt.AlignCenter)
        self.X_RValue_4.setObjectName("X_RValue_4")
        self.X_Lbar_W_0 = QtWidgets.QLabel(Dialog)
        self.X_Lbar_W_0.setGeometry(QtCore.QRect(710, 340, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.X_Lbar_W_0.setFont(font)
        self.X_Lbar_W_0.setStyleSheet("border:1px solid rgb(165, 165, 165);\n"
"")
        self.X_Lbar_W_0.setText("")
        self.X_Lbar_W_0.setAlignment(QtCore.Qt.AlignCenter)
        self.X_Lbar_W_0.setObjectName("X_Lbar_W_0")
        self.X_Lbar_0 = QtWidgets.QProgressBar(Dialog)
        self.X_Lbar_0.setGeometry(QtCore.QRect(720, 350, 141, 18))
        self.X_Lbar_0.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.X_Lbar_0.setStyleSheet("QProgressBar {border:0px;background:rgb(255, 255, 255);} QProgressBar::chunk {background: rgb(185, 0, 0);}\n"
"color:black;")
        self.X_Lbar_0.setMaximum(100)
        self.X_Lbar_0.setProperty("value", 0)
        self.X_Lbar_0.setAlignment(QtCore.Qt.AlignCenter)
        self.X_Lbar_0.setTextVisible(False)
        self.X_Lbar_0.setObjectName("X_Lbar_0")
        self.X_Lbar_W_1 = QtWidgets.QLabel(Dialog)
        self.X_Lbar_W_1.setGeometry(QtCore.QRect(710, 380, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.X_Lbar_W_1.setFont(font)
        self.X_Lbar_W_1.setStyleSheet("border:1px solid rgb(165, 165, 165);\n"
"")
        self.X_Lbar_W_1.setText("")
        self.X_Lbar_W_1.setAlignment(QtCore.Qt.AlignCenter)
        self.X_Lbar_W_1.setObjectName("X_Lbar_W_1")
        self.X_Lbar_1 = QtWidgets.QProgressBar(Dialog)
        self.X_Lbar_1.setGeometry(QtCore.QRect(720, 390, 141, 18))
        self.X_Lbar_1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.X_Lbar_1.setStyleSheet("QProgressBar {border:0px;background:rgb(255, 255, 255);} QProgressBar::chunk {background: rgb(185, 0, 0);}\n"
"color:black;")
        self.X_Lbar_1.setProperty("value", 0)
        self.X_Lbar_1.setAlignment(QtCore.Qt.AlignCenter)
        self.X_Lbar_1.setTextVisible(False)
        self.X_Lbar_1.setObjectName("X_Lbar_1")
        self.X_Lbar_W_2 = QtWidgets.QLabel(Dialog)
        self.X_Lbar_W_2.setGeometry(QtCore.QRect(710, 420, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.X_Lbar_W_2.setFont(font)
        self.X_Lbar_W_2.setStyleSheet("border:1px solid rgb(165, 165, 165);\n"
"")
        self.X_Lbar_W_2.setText("")
        self.X_Lbar_W_2.setAlignment(QtCore.Qt.AlignCenter)
        self.X_Lbar_W_2.setObjectName("X_Lbar_W_2")
        self.X_Lbar_2 = QtWidgets.QProgressBar(Dialog)
        self.X_Lbar_2.setGeometry(QtCore.QRect(720, 430, 141, 18))
        self.X_Lbar_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.X_Lbar_2.setStyleSheet("QProgressBar {border:0px;background:rgb(255, 255, 255);} QProgressBar::chunk {background: rgb(185, 0, 0);}\n"
"color:black;")
        self.X_Lbar_2.setProperty("value", 0)
        self.X_Lbar_2.setAlignment(QtCore.Qt.AlignCenter)
        self.X_Lbar_2.setTextVisible(False)
        self.X_Lbar_2.setObjectName("X_Lbar_2")
        self.X_Lbar_W_3 = QtWidgets.QLabel(Dialog)
        self.X_Lbar_W_3.setGeometry(QtCore.QRect(710, 460, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.X_Lbar_W_3.setFont(font)
        self.X_Lbar_W_3.setStyleSheet("border:1px solid rgb(165, 165, 165);\n"
"")
        self.X_Lbar_W_3.setText("")
        self.X_Lbar_W_3.setAlignment(QtCore.Qt.AlignCenter)
        self.X_Lbar_W_3.setObjectName("X_Lbar_W_3")
        self.X_Lbar_3 = QtWidgets.QProgressBar(Dialog)
        self.X_Lbar_3.setGeometry(QtCore.QRect(720, 470, 141, 18))
        self.X_Lbar_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.X_Lbar_3.setStyleSheet("QProgressBar {border:0px;background:rgb(255, 255, 255);} QProgressBar::chunk {background: rgb(185, 0, 0);}\n"
"color:black;")
        self.X_Lbar_3.setProperty("value", 0)
        self.X_Lbar_3.setAlignment(QtCore.Qt.AlignCenter)
        self.X_Lbar_3.setTextVisible(False)
        self.X_Lbar_3.setObjectName("X_Lbar_3")
        self.X_Lbar_W_4 = QtWidgets.QLabel(Dialog)
        self.X_Lbar_W_4.setGeometry(QtCore.QRect(710, 500, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.X_Lbar_W_4.setFont(font)
        self.X_Lbar_W_4.setStyleSheet("border:1px solid rgb(165, 165, 165);\n"
"")
        self.X_Lbar_W_4.setText("")
        self.X_Lbar_W_4.setAlignment(QtCore.Qt.AlignCenter)
        self.X_Lbar_W_4.setObjectName("X_Lbar_W_4")
        self.X_Lbar_4 = QtWidgets.QProgressBar(Dialog)
        self.X_Lbar_4.setGeometry(QtCore.QRect(720, 510, 141, 18))
        self.X_Lbar_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.X_Lbar_4.setStyleSheet("QProgressBar {border:0px;background:rgb(255, 255, 255);} QProgressBar::chunk {background: rgb(185, 0, 0);}\n"
"color:black;")
        self.X_Lbar_4.setProperty("value", 0)
        self.X_Lbar_4.setAlignment(QtCore.Qt.AlignCenter)
        self.X_Lbar_4.setTextVisible(False)
        self.X_Lbar_4.setObjectName("X_Lbar_4")
        self.X_Rbar_W_0 = QtWidgets.QLabel(Dialog)
        self.X_Rbar_W_0.setGeometry(QtCore.QRect(710, 540, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.X_Rbar_W_0.setFont(font)
        self.X_Rbar_W_0.setStyleSheet("border:1px solid rgb(165, 165, 165);\n"
"")
        self.X_Rbar_W_0.setText("")
        self.X_Rbar_W_0.setAlignment(QtCore.Qt.AlignCenter)
        self.X_Rbar_W_0.setObjectName("X_Rbar_W_0")
        self.X_Rbar_0 = QtWidgets.QProgressBar(Dialog)
        self.X_Rbar_0.setGeometry(QtCore.QRect(860, 550, 141, 19))
        self.X_Rbar_0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.X_Rbar_0.setAutoFillBackground(False)
        self.X_Rbar_0.setStyleSheet("QProgressBar {border:0px solid rgb(145, 145, 145);background:rgb(255, 255, 255);} QProgressBar::chunk {background:  rgb(15, 27, 255);}")
        self.X_Rbar_0.setMaximum(100)
        self.X_Rbar_0.setProperty("value", 0)
        self.X_Rbar_0.setAlignment(QtCore.Qt.AlignCenter)
        self.X_Rbar_0.setTextVisible(False)
        self.X_Rbar_0.setObjectName("X_Rbar_0")
        self.X_Rbar_W_1 = QtWidgets.QLabel(Dialog)
        self.X_Rbar_W_1.setGeometry(QtCore.QRect(710, 580, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.X_Rbar_W_1.setFont(font)
        self.X_Rbar_W_1.setStyleSheet("border:1px solid rgb(165, 165, 165);\n"
"")
        self.X_Rbar_W_1.setText("")
        self.X_Rbar_W_1.setAlignment(QtCore.Qt.AlignCenter)
        self.X_Rbar_W_1.setObjectName("X_Rbar_W_1")
        self.X_Rbar_1 = QtWidgets.QProgressBar(Dialog)
        self.X_Rbar_1.setGeometry(QtCore.QRect(860, 590, 141, 19))
        self.X_Rbar_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.X_Rbar_1.setAutoFillBackground(False)
        self.X_Rbar_1.setStyleSheet("QProgressBar {border:0px solid rgb(145, 145, 145);background:rgb(255, 255, 255);} QProgressBar::chunk {background:  rgb(15, 27, 255);}")
        self.X_Rbar_1.setMaximum(100)
        self.X_Rbar_1.setProperty("value", 0)
        self.X_Rbar_1.setAlignment(QtCore.Qt.AlignCenter)
        self.X_Rbar_1.setTextVisible(False)
        self.X_Rbar_1.setObjectName("X_Rbar_1")
        self.X_Rbar_W_2 = QtWidgets.QLabel(Dialog)
        self.X_Rbar_W_2.setGeometry(QtCore.QRect(710, 620, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.X_Rbar_W_2.setFont(font)
        self.X_Rbar_W_2.setStyleSheet("border:1px solid rgb(165, 165, 165);\n"
"")
        self.X_Rbar_W_2.setText("")
        self.X_Rbar_W_2.setAlignment(QtCore.Qt.AlignCenter)
        self.X_Rbar_W_2.setObjectName("X_Rbar_W_2")
        self.X_Rbar_2 = QtWidgets.QProgressBar(Dialog)
        self.X_Rbar_2.setGeometry(QtCore.QRect(860, 630, 141, 19))
        self.X_Rbar_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.X_Rbar_2.setAutoFillBackground(False)
        self.X_Rbar_2.setStyleSheet("QProgressBar {border:0px solid rgb(145, 145, 145);background:rgb(255, 255, 255);} QProgressBar::chunk {background:  rgb(15, 27, 255);}")
        self.X_Rbar_2.setMaximum(100)
        self.X_Rbar_2.setProperty("value", 0)
        self.X_Rbar_2.setAlignment(QtCore.Qt.AlignCenter)
        self.X_Rbar_2.setTextVisible(False)
        self.X_Rbar_2.setObjectName("X_Rbar_2")
        self.X_Rbar_W_3 = QtWidgets.QLabel(Dialog)
        self.X_Rbar_W_3.setGeometry(QtCore.QRect(710, 660, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.X_Rbar_W_3.setFont(font)
        self.X_Rbar_W_3.setStyleSheet("border:1px solid rgb(165, 165, 165);\n"
"")
        self.X_Rbar_W_3.setText("")
        self.X_Rbar_W_3.setAlignment(QtCore.Qt.AlignCenter)
        self.X_Rbar_W_3.setObjectName("X_Rbar_W_3")
        self.X_Rbar_3 = QtWidgets.QProgressBar(Dialog)
        self.X_Rbar_3.setGeometry(QtCore.QRect(860, 670, 141, 19))
        self.X_Rbar_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.X_Rbar_3.setAutoFillBackground(False)
        self.X_Rbar_3.setStyleSheet("QProgressBar {border:0px solid rgb(145, 145, 145);background:rgb(255, 255, 255);} QProgressBar::chunk {background:  rgb(15, 27, 255);}")
        self.X_Rbar_3.setMaximum(100)
        self.X_Rbar_3.setProperty("value", 0)
        self.X_Rbar_3.setAlignment(QtCore.Qt.AlignCenter)
        self.X_Rbar_3.setTextVisible(False)
        self.X_Rbar_3.setObjectName("X_Rbar_3")
        self.X_Rbar_W_4 = QtWidgets.QLabel(Dialog)
        self.X_Rbar_W_4.setGeometry(QtCore.QRect(710, 700, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.X_Rbar_W_4.setFont(font)
        self.X_Rbar_W_4.setStyleSheet("border:1px solid rgb(165, 165, 165);\n"
"")
        self.X_Rbar_W_4.setText("")
        self.X_Rbar_W_4.setAlignment(QtCore.Qt.AlignCenter)
        self.X_Rbar_W_4.setObjectName("X_Rbar_W_4")
        self.X_Rbar_4 = QtWidgets.QProgressBar(Dialog)
        self.X_Rbar_4.setGeometry(QtCore.QRect(860, 710, 141, 19))
        self.X_Rbar_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.X_Rbar_4.setAutoFillBackground(False)
        self.X_Rbar_4.setStyleSheet("QProgressBar {border:0px solid rgb(145, 145, 145);background:rgb(255, 255, 255);} QProgressBar::chunk {background:  rgb(15, 27, 255);}")
        self.X_Rbar_4.setMaximum(100)
        self.X_Rbar_4.setProperty("value", 0)
        self.X_Rbar_4.setAlignment(QtCore.Qt.AlignCenter)
        self.X_Rbar_4.setTextVisible(False)
        self.X_Rbar_4.setObjectName("X_Rbar_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Title.setText(_translate("Dialog", "신용 평가 데이터기반 평가 결과 설명 모델"))
        self.Prob1.setFormat(_translate("Dialog", "%p%"))
        self.Select_File.setText(_translate("Dialog", "신용평가 데이터 \n"
"선택하기"))
        self.Execution.setText(_translate("Dialog", "신용평가 데이터 \n"
"분석하기"))
        self.Prob1_Text.setText(_translate("Dialog", "Good"))
        self.Prob2_Text.setText(_translate("Dialog", "Bad"))
        self.Classification_Result.setText(_translate("Dialog", "분류 결과"))
        self.X_Text.setText(_translate("Dialog", "설명 결과"))
        self.pushButton_pre.setText(_translate("Dialog", "설명 모델          LIME       SHAP"))
        self.Input_Title.setText(_translate("Dialog", "사용자 입력 정보"))
        self.Value_Title.setText(_translate("Dialog", "값"))
        self.X_Title.setText(_translate("Dialog", "결과에 대한 각 정보의 기여도"))
        self.X_Lbar_0.setFormat(_translate("Dialog", "%p%"))
        self.X_Lbar_1.setFormat(_translate("Dialog", "%p%"))
        self.X_Lbar_2.setFormat(_translate("Dialog", "%p%"))
        self.X_Lbar_3.setFormat(_translate("Dialog", "%p%"))
        self.X_Lbar_4.setFormat(_translate("Dialog", "%p%"))
        self.X_Rbar_0.setFormat(_translate("Dialog", "%p%"))
        self.X_Rbar_1.setFormat(_translate("Dialog", "%p%"))
        self.X_Rbar_2.setFormat(_translate("Dialog", "%p%"))
        self.X_Rbar_3.setFormat(_translate("Dialog", "%p%"))
        self.X_Rbar_4.setFormat(_translate("Dialog", "%p%"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

